### PR TITLE
added flask server, related to issue #8

### PR DESCRIPTION
**Pull request by bartekspitza**
# Description

Please include a summary of the change and which issue is fixed. 
Please also include relevant motivation and context. 
List any dependencies that are required for this change.

Fixed issue #8 

# How Has This Been Tested?

The server has been up and running on my machine and was able to retrieve requests. 

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by platisd — COMMENTED** [review]
Do you really need to commit all these files, e.g. in the `server/venv/`?

**Comment by bartekspitza** [comment]
> Do you really need to commit all these files, e.g. in the `server/venv/`?

You're right. Removed the folder and added requirements.txt instead.

**Review by platisd — COMMENTED** [review]
For me it looks fine now, but your group-mates should approve. :smirk:

**Review by jay-py — APPROVED** [review]

**Comment by platisd** [comment]
Just a tip: You can automatically close/fix issues by using the correct terminology in your pull request or commit. Specifically, if you would have written `Fixes #8` or `Fixed #8` the relevant issue would have been automatically closed. You can read more [here](https://help.github.com/en/articles/closing-issues-using-keywords).

**Pull request merged**
